import Head from 'next/head'
import React from "react";
import Navbar from "../components/Navbar";
import Image from 'next/image'
import Footer from '../components/footer';
import SocialMedia from '../components/SocialMedia';

export default function About(){
    return(
        <div className=" w-full h-full flex-1 bg-[#121212] lg:bg-[#000] flex flex-col ">
            <Head>
            <title>About Shot by Dara Studios</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head> 
            <Navbar tab='about' />
            <div className=" pt-10 pb-32 w-full px-6 xl:px-44 lg:px-24  " > 
                <div className="  lg:mt-0 mt-12 bg-[#121212] w-full flex lg:flex-row flex-col items-center  " > 
                    <div className=' w-full flex lg:mt-0 mt-6  ' > 
                        <img  src="/images/About1.png" alt='one' className=' w-full object-cover ' /> 
                    </div> 
                    <div className=' w-full flex  text-white h-full flex-col ' >
                       <div className=' lg:px-24 xl:px-24 lg:mt-0 mt-10 ' > 
                            <p className=' font-Poppins-ExtraBold lg:text-4xl text-2xl lg:text-left text-center leading-snug ' >My name is Idara Adiakpan,</p>
                            <p className=' font-Poppins-ExtraBold lg:text-4xl text-2xl lg:text-left text-center lg:mt-5 text-[#C48F56] '>I’m a Photographer.</p> 
                            <p className=' font-Poppins-Regular mt-4 lg:text-left text-center' >The world without photography will be meaningless to us if there is no light and color, which opens up our minds and expresses passion.</p>
                            <p className=' font-Poppins-Regular mt-4 lg:text-left text-center'>I hail from Akwa Ibom State, Nigeria. My style is a combination between photojournalism, fine-art photography, documentary photography, with a touch of fashion and creative lighting. My photos are inspired by light, color, techniques from black & white processing, vintage photos, creative perspective,  and of course, most importantly, the personalities of the people i photograph!</p>
                       </div>
                    </div >
                </div>
                <div className="  mt-10 lg:mt-24 bg-[#121212]   w-full flex lg:flex-row flex-col items-center  " > 
                    <div className=' w-full flex  text-white h-full flex-col ' >
                       <div className=' lg:px-24 xl:px-24 ' > 
                            <p className=' font-Poppins-Bold text-[35px] leading-snug lg:text-left text-center' >My Skills</p>
                            <div className=' w-full grid-col-1 grid lg:grid-cols-2 gap-6 ' >
                                <div className=' w-full ' >
                                    <p className=' font-Poppins-SemiBold mt-4 text-xl lg:text-left text-center' >PORTRAITS</p>
                                    <p className=' font-Poppins-Regular mt-2 text-sm lg:text-left text-center' >Beautiful head shots to reveal your true essence</p>
                                </div>
                                <div className=' w-full ' >
                                    <p className=' font-Poppins-SemiBold mt-4 text-xl lg:text-left text-center' >LIFESTYLE</p>
                                    <p className=' font-Poppins-Regular mt-2 text-sm lg:text-left text-center' >Make your event come alive
                                        with good impressions</p>
                                </div>
                                <div className=' w-full ' >
                                    <p className=' font-Poppins-SemiBold mt-4 text-xl lg:text-left text-center' >STUDIO</p>
                                    <p className=' font-Poppins-Regular mt-2 text-sm lg:text-left text-center' >Bringing your imaginaitons to life
                                        thereby  leaving long and lasting 
                                        memories</p>
                                </div>
                                <div className=' w-full ' >
                                    <p className=' font-Poppins-SemiBold mt-4 text-xl lg:text-left text-center' >FASHION</p>
                                    <p className='  font-Poppins-Regular mt-2 text-sm lg:text-left text-center' >Being able to capture the beatiful
                                        craft of brands with new and existing
                                        styles.</p>
                                </div>
                            </div> 
                            {/* <p className=' font-Poppins-Regular mt-4 ' >The world without photography will be meaningless to us if there is no light and color, which opens up our minds and expresses passion.</p>
                            <p className=' font-Poppins-Regular mt-4 '>I hail from Akwa Ibom State, Nigeria. My style is a combination between photojournalism, fine-art photography, documentary photography, with a touch of fashion and creative lighting. My photos are inspired by light, color, techniques from black & white processing, vintage photos, creative perspective,  and of course, most importantly, the personalities of the people i photograph!</p> */}
                       </div>
                    </div >
                    <div className=' w-full flex lg:mt-0 mt-10  ' > 
                        <img  src="/images/About.png" alt='one' className=' w-full object-cover ' /> 
                    </div> 
                </div> 
                <div className=' w-full mt-14 text-white ' >
                    <p className=' font-Poppins-Bold text-2xl lg:text-[35px] text-center leading-snug ' >Why Choose Me (<span className=' text-[#C48F56] ' >Us</span>)?</p>
                    <div className=' w-full grid grid-cols-1 lg:grid-cols-3 gap-6 mt-6 ' >
                        <div className=' w-full flex flex-col lg:items-start ' >
                            <p className=' font-Poppins-SemiBold mt-4 text-xl lg:text-left text-center ' >LIGHT COMPOSURE</p>
                            <p className=' font-Poppins-Regular lg:w-[300px] mt-2 text-sm lg:text-left text-center ' >With our state of the art lighting equipment, you 
                                can be sure to have stunning images captured in
                                the idea lighting environment.</p>
                        </div>
                        <div className=' w-full flex flex-col items-center  ' >
                            <p className=' font-Poppins-SemiBold mt-4 text-xl text-center ' >PROFESSIONAL SKILLS</p>
                            <p className=' font-Poppins-Regular lg:w-[300px] mt-2 text-sm text-center ' >I have been able to capture real-life events
                                and milestones in a very artistic manner.</p>
                        </div>
                        <div className=' w-full flex flex-col items-center lg:items-end' >
                            <p className=' font-Poppins-SemiBold mt-4 text-xl text-center lg:text-right ' >PERFECT EQUIPMENT</p>
                            <p className=' font-Poppins-Regular lg:w-[300px] mt-2 text-sm text-center lg:text-right ' >The world without photography will be
                                meaningless to us if there is light.</p>
                        </div>
                        <div className=' w-full flex flex-col items-center lg:items-start' >
                            <p className=' font-Poppins-SemiBold mt-4 text-xl  lg:text-left text-center ' >ULTRA HD</p>
                            <p className=' font-Poppins-Regular lg:w-[300px] mt-2 text-sm lg:text-left text-center ' >Our captures go beyond a smiling face.
                                It is also about your personality.</p>
                        </div>
                        <div className=' w-full flex flex-col items-center lg:items-center ' >
                            <p className=' font-Poppins-SemiBold mt-4 text-xl text-center ' >UNIC VISION</p>
                            <p className=' font-Poppins-Regular lg:w-[300px] mt-2 text-sm text-center ' >Your brand story is sure to be comunicated
                                to your customers boldly, bringing art and
                                commerce together.</p>
                        </div>
                        <div className=' w-full flex flex-col items-center lg:items-end' >
                            <p className=' font-Poppins-SemiBold mt-4 text-xl text-center lg:text-right ' >FOCUSING KNOWLEDGES</p>
                            <p className=' font-Poppins-Regular lg:w-[300px] mt-2 text-sm text-center lg:text-right ' >I love my work! I want to believe you would like to 
                                have a feel of what it takes to work with a dark, 
                                bold, and creative female photographer like me.</p>
                        </div>
                    </div>
                </div>
            </div>
            <SocialMedia />
            <Footer />
        </div>
    )
}