import Head from 'next/head'
import React from "react";
import Navbar from "../components/Navbar";
import Image from 'next/image'
import Footer from '../components/footer';

export default function About(){
    return(
        <div className=" w-full h-full flex-1 bg-[#0f0f0f] flex flex-col ">
            <Head>
            <title>About Shot by Dara Studios</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head> 
            <Navbar tab='about' />
            <div className=" pt-10 w-full  " > 
                <div className=" py-6 lg:mt-0 mt-12 lg:py-20 w-full px-6 flex lg:flex-row flex-col-reverse items-center  " >
                    <div className=' w-full  lg:mt-0 mt-6  ' > 
                    <img src="/images/One.png" alt='one' className=' w-full lg:w-639px lg:h-702px ' /> 
                    </div>
                    <div className=' w-full relative flex lg:px-28 text-white h-full flex-1 flex-col justify-center items-center ' >
                    <p className='NotoSan-600 lg:text-2xl lg:w-[529px] lg:text-right lg:absolute text-center mb-6 lg:mb-0 lg:mr-28 -top-40  z-20'>About</p>
                    <p className='lg:w-[529px] NotoSan-300 lg:text-2xl' >My name is Idara Adiakpan, I’m from Akwa Ibom State, Nigeria.
I’m a graduate of theatre arts from the University Uyo I also studied the art of digital photography at the Losgiddy School of Photography Lagos.</p>
                    </div >
                </div>
                <div className=" py-6 lg:py-20 w-full px-6 flex lg:flex-row flex-col items-center  " >
                    <div className=' w-full flex lg:px-28 text-white h-full justify-center items-center ' >
                    <p className='lg:w-[529px] NotoSan-300 lg:text-2xl' >Photography is more than just a passion, It is a medium for me to express myself, to tell stories, give people new perspectives and ways of seeing the world and I also love the creative process. 
I shoot for a great variety of projects, doing Portrait, Fashion, Beauty and Documentary.


</p>
                    </div >
                    <div className=' w-full  lg:mt-0 mt-6  ' > 
                    <img  src="/images/Two.png" alt='one' className=' w-full lg:w-639px lg:h-702px ' /> 
                    </div> 
                </div>
            </div>
            <Footer />
        </div>
    )
}