import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import Navbar from '../components/Navbar'
import SliderComponent from '../components/SliderComponent'
import SliderCOmponent from '../components/SliderComponent'

export default function Index() {

    const [next, setNext] = React.useState(0) 

    return (
            <div className=" w-full h-screen flex-1 overflow-hidden bg-[#0F0F0F] flex flex-col ">
                <Head>
                    <title>Shot by Dara Studios</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head> 
                <Navbar tab='home' />
                <div className=' flex w-full h-screen pb-44' >
                    <div className=' w-[60px] hidden lg:flex flex-col ' >
                        <div id='SideText' className=' h-full flex justify-center items-center px-4 text-white w-full font-Poppins-Medium ' >
                            <img src="/images/Twitter.png" className=' -rotate-90 w-3 mt-8 '  /><Link href="" > twitter</Link>
                        </div>
                        <div className=' w-full ' > 
                            <div style={{borderRadius: "999px", width: "5px", height: "5px"}} className='mx-auto  bg-[#C48F56] ' />
                        </div>
                        <div id='SideText' className=' h-full flex justify-center items-center px-4 text-white w-full ' >
                            <img src="/images/Instagram.png" className=' w-3 mt-8 '  /><Link href="" >instagram</Link>
                        </div>
                        <div className=' w-full ' > 
                            <div style={{borderRadius: "999px", width: "5px", height: "5px"}} className='mx-auto  bg-[#C48F56] ' />
                        </div>
                        <div id='SideText' className=' h-full flex justify-center items-center px-4 text-white w-full ' >
                            <img src="/images/Facebook.png" className=' w-3 mt-8 '  /><Link href="" >facebook</Link>
                        </div>
                    </div>
                    <SliderComponent next={setNext} />
                    <div className=' w-[60px] hidden lg:flex flex-col ' >
                        <div id='SideText' className=' h-full flex justify-center items-center px-4 text-white w-full font-Poppins-Medium ' >
                            <img src="/images/Twitter.png" className=' -rotate-90 w-3 mt-8 '  /><Link href="" > CATEGORIES</Link>
                        </div>
                        <div className=' w-full ' > 
                            <div style={{borderRadius: "999px", width: "5px", height: "5px"}} className='mx-auto  bg-[#C48F56] ' />
                        </div>
                        <div id='SideText' className=' h-full flex justify-center items-center pl-1 text-white w-full ' >
                            <div className=' py-4 w-full flex items-center rounded bg-[#1D1D1D] ' >
                                <img src="/images/close.png" className=' w-3 mt-8 '  /><Link href="" >CLOSE</Link>
                            </div>
                        </div> 
                    </div>
                </div>
                <div className=' w-full font-Poppins-Regular  pt-2 bg-[#0F0F0F] absolute bottom-0 px-[60px] pb-3 ' >
                    <div className=' w-full hidden lg:flex justify-end items-center ' >
                        <p className={next === 0 ? ' text-[#C48F56] mx-2 ' : ' text-white mx-2 ' } >01</p>
                        {next === 0 && (
                            <div className=' h-[1px] bg-white w-6 mx-2 ' />
                        )}
                        <p className={next === 1 ? ' text-[#C48F56] mx-2 ' : ' text-white mx-2 ' }>02</p>
                        {next === 1 && (
                            <div className=' h-[1px] bg-white w-6 mx-2 ' />
                        )}
                        <p className={next === 2 ? ' text-[#C48F56] mx-2 ' : ' text-white mx-2 ' }>03</p>
                    </div>

                    <div className=' w-full flex lg:hidden relative pb-2' >
                        <div className=' h-full flex justify-center items-center px-4 text-white w-full font-Poppins-Medium ' >
                            <Link href="" > CATEGORIES</Link>
                        </div>
                        <div className=' w-full absolute flex justify-center ' > 
                            <div style={{borderRadius: "999px", width: "5px", height: "5px"}}  />
                        </div>
                        <div className=' h-full flex justify-center items-center pl-1 text-white w-full ' > 
                                <Link href="" >ABOUT</Link> 
                        </div> 
                    </div>
                </div>
            </div>
    )
}
