import React from "react";
import Navbar from "../components/Navbar";
import Head from 'next/head'
import Footer from "../components/footer";

export default function Portfolio(){

    const [tab, setTab] = React.useState(0)

    return(
        <div className=" w-full h-full flex-1 bg-[#0f0f0f] flex flex-col ">
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head> 
            <Navbar tab='portfolio' />
            <div className=" pt-36 w-full flex justify-center " >
                <div className=" NotoSan-500 flex flex-col" >
                    <button onClick={()=> setTab(0)} className={tab === 0 ? "text-white my-2" : "text-[#A1A1A1] my-2"}>BEAUTY</button>
                    <button onClick={()=> setTab(1)} className={tab === 1 ? "text-white my-2" : "text-[#A1A1A1] my-2"}>LIFESTYLE</button>
                    <button onClick={()=> setTab(2)} className={tab === 2 ? "text-white my-2" : "text-[#A1A1A1] my-2"}>FAMILY PORTRAIT</button>
                    <button onClick={()=> setTab(3)} className={tab === 3 ? "text-white my-2" : "text-[#A1A1A1] my-2"}>PORTRAIT</button>
                    <button onClick={()=> setTab(4)} className={tab === 4 ? "text-white my-2" : "text-[#A1A1A1] my-2"}>DOCUMENTARY</button>
                </div>
                {tab === 0 && ( 
                    <div className=" flex flex-col ml-20 mb-20 " >
                        <div className=" grid grid-cols-2 gap-6" >
                            <img src="/images/Beauty/1.png" className=" w-80" />
                            <img src="/images/Beauty/2.png" className=" w-80" />
                            <img src="/images/Beauty/3.png" className=" w-80" />
                            <img src="/images/Beauty/4.png" className=" w-80" />
                            <img src="/images/Beauty/5.png" className=" w-80" />
                            <img src="/images/Beauty/6.png" className=" w-80" />
                            <img src="/images/Beauty/7.png" className=" w-80" />
                            <img src="/images/Beauty/8.png" className=" w-80" />
                        </div>
                    </div>
                )}
                {tab === 1 && ( 
                    <div className=" flex flex-col ml-20 mb-20 " >
                        <div className="flex flex-col" >
                            <div className=" flex " >
                                <img src="/images/lifestyle/1.png" className=" w-80 mr-3" />
                                <img src="/images/lifestyle/5.png" className=" w-80 ml-3" />
                            </div>
                            <img src="/images/lifestyle/2.png" className=" w-full my-6" />
                            <div className=" flex " >
                                <img src="/images/lifestyle/3.png" className=" w-80 mr-3" />
                                <img src="/images/lifestyle/6.png" className=" w-80 ml-3" />
                            </div>
                            <img src="/images/lifestyle/4.png" className=" w-full my-6" />
                        </div> 
                    </div>
                )}
                {tab === 2 && ( 
                    <div className=" flex flex-col ml-20 mb-20 " >
                        <div className=" grid grid-cols-2 gap-6" >
                            <img src="/images/family/2.png" className=" w-80" />
                            <img src="/images/Beauty/5.png" className=" w-80" />
                            <img src="/images/family/3.png" className=" w-80" />
                            <img src="/images/family/4.png" className=" w-80" />
                            <img src="/images/family/5.png" className=" w-80" />
                            <img src="/images/family/6.png" className=" w-80" />
                            <img src="/images/family/7.png" className=" w-80" />
                            <img src="/images/family/8.png" className=" w-80" />
                        </div>
                    </div>
                )}
                {tab === 3 && ( 
                    <div className=" flex flex-col ml-20 mb-20 " >
                        <div className=" grid grid-cols-2 gap-6" >
                            <img src="/images/Portrait/1.png" className=" w-80" />
                            <img src="/images/Portrait/2.png" className=" w-80" />
                            <img src="/images/Portrait/3.png" className=" w-80" />
                            <img src="/images/Portrait/4.png" className=" w-80" />
                            <img src="/images/Portrait/5.png" className=" w-80" />
                            <img src="/images/Portrait/6.png" className=" w-80" />
                            <img src="/images/Portrait/7.png" className=" w-80" />
                            <img src="/images/Portrait/8.png" className=" w-80" />
                        </div>
                    </div>
                )}
                {tab === 4 && ( 
                    <div className=" flex flex-col ml-20 mb-20 " >
                        <div className=" grid grid-cols-2 gap-6" >
                            <img src="/images/Documentary/1.png" className=" w-80" />
                            <img src="/images/Documentary/2.png" className=" w-80" />
                            <img src="/images/Documentary/3.png" className=" w-80" />
                            <img src="/images/Documentary/4.png" className=" w-80" />
                            <img src="/images/Documentary/5.png" className=" w-80" />
                            <img src="/images/Documentary/6.png" className=" w-80" />
                            <img src="/images/Documentary/7.png" className=" w-80" />
                            <img src="/images/Documentary/8.png" className=" w-80" />
                        </div>
                    </div>
                )}
            </div>
            <Footer />
        </div>
    )
}